### ISSUE TITLE
Please set suitable permission to enable joystick support usage

### ISSUE THREAD

**Issue by Nokia808** [flathub/com.alientrap.nexuiz-classic#1]
Hi. I downloaded this game & tried to play it. The problem is that you did not set needed permission to enable support of joystick by user if she/he like use. 

The game by itself support use of joystick. But in this flatpak, activating support of joystick from UI of game currently does not working.

I think that this due to the fact that you did not set "device=all" permission.

Kindly to fix this.

Thank you very much for offering this nice game on flatHub

**Comment by rszibele** [comment]
Hi, I've added device access to the Flatpak with commit https://github.com/flathub/com.alientrap.nexuiz-classic/commit/b695373ef652ad208ff02f2a12b2062bfdc354a4, so it should work now once the changes propagate to the Flathub repository. While the solution isn't ideal, it does not seem like there is currently any better solution than simply allowing access to all devices https://github.com/flatpak/flatpak/issues/7.

Please comment on this issue if it doesn't solve it and I'll re-open it, as I do not have a controller or joystick at hand to test it.

**Comment by Nokia808** [comment]
@rszibele 
It work now. Thank you for the fix.
However, I see this game is a mimic of Xonotic ! What the difference between it & Xonotic ?

**Comment by rszibele** [comment]
@Nokia808 That's great to hear.

Xonotic is a fork and further development of Nexuiz. They are both still being played online and Nexuiz has some older multiplayer mods that I personally like, but I don't believe they were ever ported to Xonotic.
